/*
 * This source file was generated by the Gradle 'init' task
 */
package learnjava;

public class App {
    public String getGreeting() {
        return "Hello World! Its Gradle and Jenkins integration.";
    }

    public String getName(String name) {
        return "Hello " + name + "! Its Gradle and Jenkins integration.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getName("Muhammad Irfan!"));
    }
}
